### ISSUE TITLE
Use `backdrop-filter` over `filter` for background

### ISSUE THREAD

**Issue by KorbsStudio** [NyaomiDEV/Sunamu#4]
With `filter`, the framerate seems to drop when the background is changing:
https://cdn.korbsstudio.com/2022-01-15%2019-36-56.mp4

With `backdrop-filter`, seems more smooth with no frame drop:
https://cdn.korbsstudio.com/2022-01-15-19-35-58.mp4

Usually adding something basic to CSS should help, kinda like:
```css
.background::before {
     position: fixed;
     top: 0px;
     left: 0px;
     width: 100%;
     height: 100%;
     backdrop-filter: blur(64px) brightness(50%) saturate(150%);
}
```
